import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import Candidate from '../components/Candidate'
import getCombo from './api/combobox'
import { useStoreOption } from '../lib/candidate'


interface propsData {
    positionApplied: string[]
}

const CandidateForm: NextPage<propsData> = ({positionApplied}) => {
    const { setPositionApplied } = useStoreOption()

    useEffect(() => {
        setPositionApplied(positionApplied)
    }, [positionApplied])

    return(
        <>
        <Head>
            <title>Form Candidate HRMS</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <div className="p-10 min-h-screen bg-gray-200">
            <div className="bg-white shadow-md rounded-md">
                <Candidate />
            </div>
        </div>
        </>
    )
}

export const getStaticProps = async () => {
    const res = await getCombo("genre", 0);
    const positionApplied: any[] = [];

    res.map((key:any) => {
        positionApplied.push({value: key.combo_key, label: key.combo_name})
    })

    return {
        props: {
            positionApplied
        }
    }
}

export default CandidateForm